services:
  app:
    container_name: app
    build:
      context: .
    networks:
    - app
    expose:
    - 9000
    depends_on:
    - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
      DB_DATABASE: laravel
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
    - "8080:80"
    networks:
    - app
    depends_on:
    - app
    volumes:
    - .:/var/www:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    networks:
    - app
    volumes:
    - db_data:/var/lib/mysql
    restart: unless-stopped

networks:
  app: {}

volumes:
  db_data: {}