services:
  app:
    container_name: app
    build:
      context: .
    expose:
    - 9000
    depends_on:
    - mysql
    networks:
    - app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
    - "8080:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./public:/var/www:ro
    depends_on:
    - app
    networks:
    - app

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
    - db_data:/var/lib/mysql
    networks:
    - app
  
networks:
  app: {}

volumes:
  db_data: {}